CREATE TABLE `app_type_mst` (
	`APP_TYPE_CODE` VARCHAR(30) NOT NULL,
	`APP_TYPE_NAME` VARCHAR(30) NOT NULL,
	`ORD` SMALLINT(4) NOT NULL DEFAULT '0',
	PRIMARY KEY (`APP_TYPE_CODE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
