CREATE TABLE `usrtbl` (
	`ID` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
	`USER_ID` VARCHAR(50) NOT NULL,
	`FIRST_NAME` VARCHAR(30) NOT NULL,
	`LAST_NAME` VARCHAR(30) NOT NULL,
	`CI_FLG` TINYINT(4) NOT NULL DEFAULT '0',
	`VP_ID` VARCHAR(50) NOT NULL,
	`LANG_CD` VARCHAR(5) NOT NULL DEFAULT 'ja',
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
